export const accessToken =
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwibmFtZSI6IlNlcmVuYSBKb3kiLCJlbWFpbCI6InNlcmVuYUBtYWlsLmNvbSIsImlhdCI6MTczNjk3NTMwMSwiZXhwIjoxNzM3NTgwMTAxLCJhdWQiOiJ1c2VycyIsImlzcyI6ImxvZ2luIiwic3ViIjoiMiJ9.dxlJAos9MI_0wcFk0e_Fu2vm_YdKFdWIBWayyp0U6q4';
